[theme]
primaryColor = "#0078D4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#323130"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
